# Generated by Django 4.1.6 on 2023-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_passkey_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
        migrations.AlterField(
            model_name='user',
            name='passkey',
            field=models.CharField(default='haCy3YtSDZ', editable=False, max_length=10, null=True),
        ),
    ]
