# Generated by Django 4.1.6 on 2023-02-17 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_type_user_is_admin_user_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='passkey',
            field=models.CharField(default='pRq8NjYzOL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
