# Generated by Django 4.1.6 on 2023-02-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_class_label_termresult_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passkey',
            field=models.CharField(default='QHVqzyLOhw', editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yearresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_results', to='users.studentprofile'),
        ),
    ]
